# -*- coding: utf-8 -*-
"""train-ticket 终稿条目。每条的 original_ids 指向 static-audit/ 的原编号，合并依据写在 notes 里。"""

S = "train-ticket"

TT_ENTRIES = [

# ============================ 一、服务发现与启动依赖 ============================
dict(
    id="TT-01", system=S, level="R",
    title="Nacos 不可用时业务服务注册即 fail-fast 退出，CrashLoopBackOff 把恢复从秒级拖到 12 分钟",
    family=["replica_disruption（重启恢复）", "retry_backoff"], families=["replica_disruption", "retry_backoff"],
    dmode="主 D6（启动硬依赖）；次 D5（与 kubelet 退避叠加）、D3",
    flows=["全部"],
    trigger="Nacos 三副本同时未 Ready 的窗口里，任一业务 Pod 因 OOM、驱逐、节点重调度或平台重置流程 restart-application-deployments 而启动或重启。nacos-discovery 2.2.7 的 failFast 默认为 true，注册失败直接抛出导致上下文启动失败、进程退出。",
    consequence="本轮实测：Nacos 0/3 时 37 个 Pod 进入 CrashLoopBackOff，主要重启 14–17 次。Nacos 恢复（T0=08:57:44Z）后就绪中位数是 T0−97 s，但最慢的 auth、assurance 要到 T0+764 s 才回来，44 个 Pod 重启 ≥5 次。没有 startupProbe，kubelet 退避从 10 s 翻倍到 300 s 封顶，再叠加 JVM 启动和 60 s 就绪初始延迟。",
    level_why="本轮新环境直接复现，有 crashloop.txt 与 recovery-lag.txt 两份采集。恢复时长与 TT-06 的连接上限叠加，不能单独归因于本条。",
    evidence=[
        "证据/TT-startup-hard-dependency-on-nacos/crashloop.txt（08:23Z，Nacos 0/3，37 Pod CrashLoopBackOff，UnknownHostException nacos-N.nacos-headless）",
        "证据/TT-startup-hard-dependency-on-nacos/recovery-lag.txt（T0=08:57:44Z，就绪中位 −97 s、最慢 +764 s）",
        "TT源码/pom.xml:68-73（所有模块引入 nacos-discovery 2.2.7）",
        "~/.m2/repository/com/alibaba/cloud/spring-cloud-starter-alibaba-nacos-discovery/2.2.7.RELEASE（javap：failFast=true；NacosServiceRegistry.register 调 rethrowRuntimeException）",
        "清单/train-ticket/deployments.json（initContainers 为 0，无 startupProbe，readiness 初始延迟 60 s）",
    ],
    original_ids=["TT-A3", "TT-B06", "TT-E02", "TT-D13（部分）", "TT-RT-03"],
    notes="四组各从自己的链路记了同一个根因，合并为一条。TT-D13 是支付/消息组的「共性问题打包条目」，按根因拆开：启动依赖并入本条，无超时并入 TT-11，单副本无 PDB 并入 TT-29，无 liveness 并入 TT-38。voucher 不经 Nacos（server.py:47-48），是本条的天然阴性对照。",
),
dict(
    id="TT-02", system=S, level="C",
    title="服务发现的「健康」只表示 gRPC 连接还活着：Ribbon 不探活、不剔除、不重试，K8s 就绪被完全绕开",
    family=["health_probe（负载均衡层健康判定）", "replica_disruption（摘除/故障转移）", "circuit_isolation（被动剔除）"],
    families=["health_probe", "replica_disruption", "circuit_isolation"],
    dmode="主 D2（摘除与故障转移失效）；次 D4、D6",
    flows=["全部"],
    trigger="实例进程活着但已无法服务（线程耗尽、堆内 OOM、卡死），或实例被杀而 Nacos 仍把旧 IP 标为健康。网关和服务间调用都只认 Nacos 的实例列表，K8s 的 readiness 只影响 Service 端点，摘不掉 Nacos 流量。",
    consequence="失败会持续到 Nacos 自己改判为止，而不是一个探测周期。Ribbon 服务器列表每 30 s 才刷新一次，默认 DummyPing 不主动探活；网关走 LoadBalancerClientFilter 只调 choose()，不经 execute，永远不记 ServerStats，AvailabilityPredicate 不会跳闸。查询链路 6+6N 次扇出会把单实例故障放大：order 两副本时约一半请求受影响。",
    level_why="库默认值已用 javap 逐条反编译核实，清单里的探针配置也已核实。本轮新环境没有再现陈旧注册（nacos-vs-pods.txt 显示陈旧 0、登记未就绪 0），旧环境 08-22 事故复现过，因此定 C 而不是 R。",
    evidence=[
        "TT源码/ts-gateway-service/src/main/resources/application.yml:16–209（39 条路由全是 uri: lb://…）",
        "~/.m2/…/ribbon（javap：PollingServerListUpdater 首次 1000 ms、之后 30000 ms；RibbonClientConfiguration 默认 DummyPing + ZoneAvoidanceRule；LoadBalancerClientFilter 只调 choose(String)）",
        "清单/train-ticket/deployments.json（readiness 仅 tcpSocket，无 liveness）",
        "证据/TT-network-and-health/nacos-vs-pods.txt（本轮：陈旧 0、登记未就绪 0；文件头时间戳未展开）",
        "D0/environment/repairs/train-ticket-nacos-workload-qualification-20260822.yaml:8–22、:27（旧环境陈旧注册与人工修复记录）",
    ],
    original_ids=["TT-A1", "TT-A4", "TT-B03", "TT-B04", "TT-C4", "TT-E04"],
    notes="六条讲的是同一件事在不同链路上的投影：A1 是网关侧四方面根因，A4 是绕开 K8s 就绪，B03 是扇出放大，B04 是探针与路由脱节，C4 是 order 陈旧实例，E04 是两套健康判定互不相通。合并后保留 B03 的扇出放大系数。失败率随扇出放大的具体数值依赖死 IP 是快速拒连还是丢 SYN（后者每次约 127 s），两种情况差一个量级，属未核实。",
),
dict(
    id="TT-03", system=S, level="C",
    title="Nacos 三副本注册表分歧的配置层根因：成员列表用 DNS 名、没有持久卷、headless 不发布未就绪地址",
    family=["replica_disruption（服务发现）"], families=["replica_disruption"],
    dmode="主 D6；次 D4、D5",
    flows=["全部"],
    trigger="某个 Nacos 副本未 Ready 的窗口里业务 Pod 换 IP 重建。成员域名只在 Pod Ready 时才解析得到，而 Ready 又不等于 Distro 数据就绪；nacos-headless 没开 publishNotReadyAddresses。",
    consequence="三副本注册表出现分歧：调用方看到的实例列表取决于它的 gRPC 连接恰好挂在哪个副本上。旧环境曾出现已不存在的 Pod IP 被标为健康，需要人工修复。没有持久卷意味着重建即丢注册数据。",
    level_why="配置已在清单里核实（statefulsets.json、services.json、configmaps.json）。旧环境有事故与修复记录，本轮新环境未再现。",
    evidence=[
        "清单/train-ticket/statefulsets.json（Nacos 2.0.1 三副本，无持久卷）",
        "清单/train-ticket/services.json（nacos-headless 未设 publishNotReadyAddresses）",
        "清单/train-ticket/configmaps.json（成员列表用 DNS 名而非固定 Pod IP）",
        "D0/environment/repairs/train-ticket-nacos-workload-qualification-20260822.yaml:8–22（旧环境三副本分歧的处置记录）",
    ],
    original_ids=["TT-A2", "TT-E08"],
    notes="A2 从网关视角描述后果（错误路由、空列表 503），E08 给出 Nacos 集群配置层的根因，合并为一条。与 TT-02 的分工：本条是「注册表为什么会错」，TT-02 是「注册表错了为什么没人纠正」。",
),
dict(
    id="TT-04", system=S, level="R",
    title="41 个 Java 服务每次启动都要挂载集群外主机 1.94.151.57 的 NFS 取 javaagent，这台主机同时是 Harbor",
    family=["replica_disruption（重启恢复）"], families=["replica_disruption", "other"],
    dmode="D6（启动硬依赖集群外单点）",
    flows=["全部"],
    trigger="NFS 主机不可达，或节点上没有 mount.nfs。所有业务 Pod 的重建都会卡住。",
    consequence="本轮实测：46 个 Pod 停在 ContainerCreating，FailedMount 事件 13 次 / 10 分钟，报 `mount -t nfs 1.94.151.57:/data/share` bad option（节点没有 mount.nfs）。这台主机同时承载 Harbor，一旦它出问题，拉镜像和挂 agent 会同时失败，故障域完全重叠。",
    level_why="本轮新环境直接复现，有 before-fix.txt。已被偏差 #7 掩盖（agent 换成镜像内置的 otel-demo 2.2.0），现在无法再复现。",
    evidence=[
        "证据/TT-nfs-javaagent-startup-dependency/before-fix.txt（07:06Z，46 Pod ContainerCreating，FailedMount×13/10m）",
        "清单/train-ticket/deployments.json（41 个 Java Deployment 挂载 NFS 卷 1.94.151.57:/data/share，-javaagent 指向该目录）",
        "DEVIATIONS.md 偏差 #7",
    ],
    original_ids=["TT-E03", "TT-RT-02"],
    notes="旧环境是潜伏单点：依赖一直存在，只是那台主机一直可达。终稿记 R 并注明已被偏差 #7 掩盖。",
),
dict(
    id="TT-05", system=S, level="R",
    title="xenon 用「localhost=IPv4 + 免密 root」探活，K8s 探针走 Unix socket，两套判定分叉出「探针全绿但没有主库」",
    family=["health_probe", "replica_disruption（故障转移）"], families=["health_probe", "replica_disruption"],
    dmode="主 D6；次 D2（选不出主 = 故障转移失效）",
    flows=["全部"],
    trigger="Pod 里启用了 IPv6 回环时，localhost 解析到 ::1，而 mysql.user 里只有 root@127.0.0.1 和 root@localhost，root@'::1' 被拒（1045）。xenon 因此判定本地 mysqld 已死。",
    consequence="本轮实测：两个 leader Service 都没有端点，6 个 MySQL 全是 follower，xenon ping 失败计数 downs:720（downslimits:3），而 K8s 探针走 Unix socket 一路绿灯。数据库集群永久选不出主，所有写入不可用，但从 K8s 看一切正常。",
    level_why="本轮新环境直接复现（before-fix.txt），补 root@'::1' 后 10 秒内选出主。已被偏差 #5 掩盖。",
    evidence=[
        "证据/TT-xenon-ipv6-localhost/before-fix.txt（06:51Z，两个 leader Service 无端点、6 个 MySQL 全 follower、root@'::1' 1045、downs:720）",
        "TT源码/deployment/kubernetes-manifests/quickstart-k8s/charts/（Chart 的 allowEmptyRootPassword: true，xenon 经 TCP localhost:3306 免密探活）",
        "清单/train-ticket/statefulsets.json（K8s 探针走 Unix socket）",
        "DEVIATIONS.md 偏差 #5",
    ],
    original_ids=["TT-E01", "TT-RT-01"],
    notes="旧环境是潜伏状态：配置相同，但 Pod 里没启用 IPv6，所以没触发。这是「两套健康判定各自为政」在数据库层的实例，与 TT-02（服务发现层）、TT-38（应用层）同构。",
),
dict(
    id="TT-06", system=S, level="R",
    title="tsdb 实际连接上限只有 214 而稳态需求 270：configmap 写的 65535 被 open_files_limit=1024 压掉了两个数量级",
    family=["resource_limit", "load_shedding_admission"], families=["resource_limit", "load_shedding_admission"],
    dmode="主 D4（配置值与生效值不符）；次 D5、D1",
    flows=["全部"],
    trigger="服务起齐即触发，不需要注入。25 个服务共 27 个实例，每实例 Hikari 池 10，合计需求 270；MySQL 因 open_files_limit=1024 把 max_connections 从配置的 65535 自动压低到 214。",
    consequence="本轮实测：稳态 Threads_connected 276、Max_used_connections 286、Connection_errors_max_connections 127；最后启动的几个服务（assurance、order-other、security 等）直接 Too many connections 崩溃重启。这是一个「配置谎言」——运维看 configmap 会以为有 65535 个连接可用。",
    level_why="本轮新环境直接复现，有 crashloop-too-many-connections.txt 与 processlist-by-pod.txt 两份采集。偏差 #13 把上限临时 SET GLOBAL 到 400，不持久：MySQL 一重启或切主就回到 214。",
    evidence=[
        "证据/TT-db-connection-exhaustion/crashloop-too-many-connections.txt（09:04Z，assurance/order-other/security 等 Too many connections）",
        "证据/TT-db-connection-exhaustion/processlist-by-pod.txt（09:04Z，业务连接 213，Threads_connected 215 / max 214）",
        "证据/TT-tsdb-runtime-config/tsdb-leader.txt（08:59Z，@@max_connections=214、@@open_files_limit=1024）",
        "清单/train-ticket/configmaps.json（tsdb-mysql / node.cnf 写的是 max_connections=65535）",
        "证据/RES-resource-pool-metrics/during-baseline-0918.txt（25 服务 27 实例 × 池 10 = 270）",
    ],
    original_ids=["TT-E18", "TT-A12（部分）", "TT-RT-04"],
    notes="**更正静态结论**：TT-E18 担心的是「max_connections=65535 远超 1Gi 内存能承受的量」，方向反了——配置值根本没生效，实际瓶颈是 214 太小。原条目里「1 秒超时的 exec 就绪探针在 500m 限额下可能把主库误判」的部分未核实，单独留在 TT-08 的备注里。",
),

# ============================ 二、数据库高可用与存储 ============================
dict(
    id="TT-07", system=S, level="C",
    title="数据库切主不覆盖已经建立的连接：旧主变只读后连接仍能通过校验，失联时则半开挂死",
    family=["replica_disruption（故障转移）", "deadline_timeout"], families=["replica_disruption", "deadline_timeout"],
    dmode="主 D2；次 D4、D5",
    flows=["全部"],
    trigger="xenon 切主。旧主还活着时变成只读；旧主失联时连接进入半开状态。",
    consequence="旧主活着：池里的连接仍能通过 Hikari 校验（只读错误 1290 不在驱逐表里），写入持续报只读错误，直到连接因 maxLifetime 到期才轮换，约 270 条连接逐步换完最长约 30 分钟。旧主失联：JDBC 没有 socketTimeout，在用的连接半开挂死。只指向主库的 Service 在切换窗口里还可能短暂没有后端。",
    level_why="Hikari 与 JDBC 的默认行为已核实，连接数与 Secret 指向（27 个 Secret 指 tsdb-mysql-leader）已在运行时核实。切主过程本身没有实跑，30 分钟是按 maxLifetime 推算的。",
    evidence=[
        "TT源码/ts-order-service/src/main/resources/application.yml:13 等 11 个服务的 yml（JDBC URL 无 connectTimeout / socketTimeout，也没有任何 hikari 配置）",
        "证据/TT-tsdb-runtime-config/tsdb-leader.txt（27 个 Secret 的 HOST 都是 tsdb-mysql-leader）",
        "清单/train-ticket/services.json（leader Service 按标签选主，切换窗口内可能无后端）",
        "清单/train-ticket/configmaps.json（xenon 半同步与切主配置）",
    ],
    original_ids=["TT-C9", "TT-E07", "TT-B13"],
    notes="C9 从下单链路、E07 从基础设施、B13 从查询链路记同一件事，合并。「已有连接粘在旧主」这一点在三份报告里都是推断，没有实跑切主，因此不升 R。",
),
dict(
    id="TT-08", system=S, level="S",
    title="切主通告靠 curl 改 Pod 标签且不判返回码，xenon 判死阈值又过于灵敏，可能误切主并留下陈旧 leader 标签",
    family=["replica_disruption（故障转移）", "health_probe"], families=["replica_disruption", "health_probe"],
    dmode="主 D4；次 D6、D3",
    flows=["全部"],
    trigger="切主时 API Server 抖动，或 leader 被 kill -9；以及负载尖峰下 xenon 在 100m CPU 限额里约 1 秒一次探活、连续 3 次失败即判死。",
    consequence="leader-start/stop.sh 用 curl 改标签，不检查返回状态、没有超时和重试，异常失主会留下陈旧的 leader 标签，Service 指向一个已经不是主的成员。判死过灵敏则可能因为 CPU 争用误切主，进而带出 TT-07 的只读写失败。",
    level_why="脚本与阈值都在 configmap 里核实过，但误切主和陈旧标签都没有实跑复现。",
    evidence=[
        "清单/train-ticket/configmaps.json（leader-start.sh / leader-stop.sh 用 curl 改标签，无返回码判断、无超时重试）",
        "清单/train-ticket/configmaps.json（xenon 探活间隔约 1 s、连续 3 次失败判死）",
        "清单/train-ticket/statefulsets.json（xenon 容器 limit 100m/256Mi）",
    ],
    original_ids=["TT-E10", "TT-E19"],
    notes="E10 是通告机制、E19 是判死阈值，两者是同一条故障链的上下游（误判 → 切主 → 通告失败），合并。另：TT-E18 里「1 秒超时的 exec 就绪探针在 500m 限额下可能把主库误判为不可用」未核实，记在这里备查。",
),
dict(
    id="TT-09", system=S, level="C",
    title="半同步复制超时设成 1e18 且 wait_no_slave=ON，binlog 又永不过期：写入要么全局悬挂，要么把 1Gi 卷写满",
    family=["deadline_timeout", "resource_limit"], families=["deadline_timeout", "resource_limit"],
    dmode="D3（保护动作本身造成故障）",
    flows=["全部"],
    trigger="从库都不能 ACK（网络分区、从库全挂）时主库提交挂起；或长时间运行后 binlog 占满数据卷。",
    consequence="半同步 timeout=1e18 相当于无限等待，wait_no_slave=ON 表示没有从库也继续等：主库提交一直挂着，叠加客户端没有超时（TT-11、TT-12），形成全局悬挂而不是快速失败。expire_logs_days=0 表示 binlog 永不清理，xenon 也不清理，1Gi 数据卷写满后 MySQL 写入挂起而非报错。",
    level_why="配置值是 kubectl exec 进主库实测得到的（tsdb-leader.txt），不是清单推断，因此定 C；两种后果都没有实跑。",
    evidence=[
        "证据/TT-tsdb-runtime-config/tsdb-leader.txt（08:59Z，semi-sync timeout=1e18、wait_no_slave=ON、wait_point=AFTER_SYNC、wait_for_slave_count=1、expire_logs_days=0）",
        "清单/train-ticket/persistentvolumeclaims.json（数据卷 1Gi）",
    ],
    original_ids=["TT-E20", "TT-E21"],
    notes="两条都是「数据库写入悬挂」的不同触发路径，合并。E20 报告里只写了 D3、没写机制族名，这里按后果补成 deadline_timeout + resource_limit。",
),
dict(
    id="TT-10", system=S, level="C",
    title="业务库 32 张表实际是 MyISAM：表级锁、崩溃后表损坏不自修复、写入不参与两阶段提交",
    family=["other"], families=["other", "resource_limit"],
    dmode="主 D4；次 D6",
    flows=["下单", "搜索", "查单"],
    trigger="并发写同一张表时表级锁争用；进程崩溃或断电后表损坏。",
    consequence="MyISAM 只有表级锁，写并发被串行化；myisam_recover_options=OFF 表示崩溃后不自动修复；MyISAM 不支持事务，写入不参与两阶段提交，半同步复制对它没有意义。实体用 MySQL5Dialect 经 Hibernate ddl-auto 建表，默认落到 MyISAM，而 default_storage_engine 明明是 InnoDB。",
    level_why="运行时已核实 32 张 MyISAM、3 张 InnoDB（office/station/voucher）。但基线下 Table_locks_waited=0，锁争用后果没有复现——这属于 3.2 节「基线下没复现，不能判否」。",
    evidence=[
        "证据/TT-tsdb-runtime-config/tsdb-leader.txt（08:59Z，32 张 MyISAM、3 张 InnoDB、default_storage_engine=InnoDB、myisam_recover_options=OFF）",
        "证据/TT-tsdb-runtime-config/myisam-locks-during-baseline.txt（09:24Z，Table_locks_immediate 13454、waited 0）",
        "TT源码/ts-order-service/src/main/resources/application.yml:13（MySQL5Dialect + ddl-auto）",
    ],
    original_ids=["TT-C7"],
    notes="静态报告写的是「很可能被建成 MyISAM」，运行时已把它坐实，因此从 S 升到 C。锁争用要靠注入加压验证，见注入实验 G4。",
),

# ============================ 三、超时、隔离与取消 ============================
dict(
    id="TT-11", system=S, level="C",
    title="40 个服务的 RestTemplate 是 Apache HttpClient 系统默认：三种超时全无，每目标 5 条、整进程 10 条连接，借不到就无限等",
    family=["deadline_timeout", "circuit_isolation"], families=["deadline_timeout", "circuit_isolation"],
    dmode="主 D1（无截止时间）；次 D4（舱壁配错）、D5",
    flows=["全部"],
    trigger="任一下游变慢或黑洞。对 seat 注入挂起型故障（100% 丢包或 pod pause），默认负载并发 1、客户端 10 s 放弃但服务端连接继续占着，约每 10 s 多占一条，约 50 s 占满 travel→seat 的 5 个槽位，再加 travel→basic 的 5 条，全进程 10 条用尽。",
    consequence="同一个池同时承载查询和下单两条业务，所以单个慢依赖能跨路径污染：travel→seat 挂住时，下单的 /trip_detail 一起变慢。健康下游也要排队，Tomcat 200 线程逐步耗尽。清除故障后还要等 TCP 重传（上限约 120 s）才恢复，超过「清理后 60 s 恢复」的反驳线。线程栈特征是大量停在 AbstractConnPool.getPoolEntryBlocking。",
    level_why="库默认值已用 javap 在字节码层面核实（http.maxConnections 默认 \"5\"、setDefaultMaxPerRoute(5)、setMaxTotal(10)），源码里 RestTemplate 只做 builder.build() 也已核实。但部署 jar 里是否真有 httpclient、进程是否设了 -Dhttp.maxConnections 未核实（需 R10），后果也没有实跑。",
    evidence=[
        "TT源码/ts-travel-service/src/main/java/travel/TravelApplication.java:30-34（RestTemplate 只做 builder.build()，其余服务同）",
        "~/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13（javap：HttpClients.createSystem() → http.maxConnections 默认 5、maxTotal 10）",
        "~/.m2/repository/com/alibaba/cloud/spring-cloud-starter-alibaba-nacos-discovery/2.2.7.RELEASE.pom:151-155（经 netflix-ribbon → ribbon-httpclient 传递引入 httpclient）",
        "TT源码/ts-preserve-service/src/main/java/preserve/service/PreserveServiceImpl.java:32-33（同一个 RestTemplate Bean 打 11 个下游）",
        "证据/RES-resource-pool-metrics/during-baseline-0918.txt（15 分钟内无排队等连接——基线下未触发）",
    ],
    original_ids=["TT-A8", "TT-B01", "TT-C6", "TT-E05", "TT-D13（部分）", "TT-E14（部分）"],
    notes="这是全审计中跨组重复最多的一条：入口组、查询组、下单组、基础设施组各记了一次。E05 的证据最硬（字节码级），B01 的触发时序最具体（约 50 s 占满），C6 的阴性对照最清楚（撤注入后不释放）。合并后以 E05 为主干。网关侧的同一问题（39 条 lb:// 路由无超时、连接池不设上限）并入本条，Sentinel 限流部分留在 TT-30。",
),
dict(
    id="TT-12", system=S, level="C",
    title="JDBC 连接串没有 connectTimeout / socketTimeout：数据库丢包或挂起时查询无限挂起，连服务都启动不了",
    family=["deadline_timeout"], families=["deadline_timeout"],
    dmode="主 D1；次 D6",
    flows=["全部"],
    trigger="共用的 MySQL 主节点丢包、主从切换或不可用。",
    consequence="查询挂起而不是快速失败，连接池被占满；服务启动时也要连库，数据库不可用时连启动都起不来。与 TT-09 的半同步无限等待叠加后，写入会全局悬挂。",
    level_why="11 个服务的 yml 都已核实没有超时参数，也没有任何 hikari 配置。挂起后果没有实跑。",
    evidence=[
        "TT源码/ts-travel-service/src/main/resources/application.yml:13（JDBC URL 无 connectTimeout / socketTimeout；11 个服务的 yml 都搜不到 hikari 配置）",
        "证据/TT-network-and-health/probe.txt（09:01Z，tcp_syn_retries=6 tcp_retries2=15，连不存在的 IP 约 127 s 才失败）",
    ],
    original_ids=["TT-A12", "TT-B02（部分）"],
    notes="A12 是认证与用户数据访问侧，B02 的 E3 是查询链路侧，同一配置缺失。TT-06 的连接上限问题从 A12 拆出，单独成条。",
),
dict(
    id="TT-13", system=S, level="R",
    title="入口没有截止时间、取消不传播：客户端 10 s 放弃后服务端照样跑完整条链并写库，留下没人清理的幽灵订单",
    family=["deadline_timeout", "other（取消传播）"], families=["deadline_timeout", "other"],
    dmode="主 D2（取消不传播）；次 D1",
    flows=["下单", "搜索"],
    trigger="下游延迟超过压测客户端的 10 s 响应超时。网关没有响应超时配置，取消只传播到网关为止，后端和下游继续执行。",
    consequence="本轮已复现：客户端按超时判为失败，服务端却已经把订单写进库，留下一笔未支付、没人回收的订单（幽灵订单）。冷启动首请求 9.7–10 s 正好撞上这条线，第一次基线因此中止。恢复时积压的「僵尸请求」还会集中落库。",
    level_why="本轮新环境直接复现，有 TT-ghost-order-after-client-timeout/README.txt 与 TT-baseline-abort-first-run.txt 两份证据。",
    evidence=[
        "证据/TT-ghost-order-after-client-timeout/README.txt（客户端超时判失败、服务端已写单）",
        "证据/TT-baseline-abort-first-run.txt（preserve 首请求 10011 ms 码 000 失败；search 首请求 9712 ms）",
        "D0/environment/workloads/train-ticket/image/train_ticket_workload_generator.py:584-585（连接超时 3 s、响应超时 10 s，不重试）",
        "TT源码/ts-gateway-service/src/main/resources/application.yml（没有任何 timeout 键）",
        "TT源码/ts-ui-dashboard/nginx.conf:40-41（只写 proxy_pass，走默认 60 s）",
    ],
    original_ids=["TT-A7", "TT-B05", "TT-C5"],
    notes="三组各记一次：A7 是网关侧、B05 是查询链路白耗容量、C5 是下单侧写单。合并后按后果最重的下单侧定级 R。清理缺失的部分（NOTPAID 单没人回收）在 TT-18。",
),
dict(
    id="TT-14", system=S, level="C",
    title="一次查询 5+6N 次调用全部串行且有 N+1 查询，注入的延迟被放大约 2N 倍，而 N 随车次数据增长",
    family=["other（扇出放大）", "deadline_timeout"], families=["other", "deadline_timeout"],
    dmode="主 D1；次 D2",
    flows=["搜索"],
    trigger="给 seat、order 或 config 任一跳注入延迟 d。seat、order、config 这三条边的往返次数是 2N，N=1 时越过 p95≤2500 ms 只需 d≈1.1 s。",
    consequence="入口延迟增量约等于 n_rtt·d，随 d 线性增长且没有上限，全程看不到 504 或 SocketTimeoutException——只会慢失败，不会快速失败。route-plan / travel-plan 还会在此之上再串行放大，一个车次失败拖垮整个规划。",
    level_why="扇出次数已用 Jaeger 在运行时核实：一次搜索 12 次 HTTP + 19 次 DB，一次下单 28 次 HTTP + 30 次 DB，与静态推算的 5+6N（N=1 时 11 个客户端 span）吻合。延迟放大本身没有实跑注入。",
    evidence=[
        "证据/TT-call-graph-baseline/fanout.txt（搜索 HTTP 中位 12、DB 19；下单 HTTP 28、DB 30）",
        "TT源码/ts-travel-service/src/main/java/travel/service/TravelServiceImpl.java:367-375、:426-430、:550-557（seat 一等/二等各 1 次，共 2N，在 for 循环里串行）",
        "TT源码/ts-basic-service/src/main/java/fdse/microservice/service/BasicServiceImpl.java:232、:403-421（route 端 1+2R 条 SQL 懒加载）",
        "TT源码/ts-seat-service/src/main/java/seat/service/SeatServiceImpl.java:190、:205-219（config 每次远程读，2N 次）",
    ],
    original_ids=["TT-B11", "TT-B16"],
    notes="B11 是主查询链路、B16 是 route-plan/travel-plan 的二次放大，合并。B08 的 config 无缓存是本条 2N 里的一项成因，单独成条（TT-17）因为它还有 NPE 的独立后果。",
),

# ============================ 四、降级、错误处理与灰色故障 ============================
dict(
    id="TT-15", system=S, level="C",
    title="依赖失败被翻译成「成功」：travel 把 basic 故障变成 200+空列表，cancel 把任何异常包成 status=1，SLO 对故障失明",
    family=["fallback_degradation"], families=["fallback_degradation"],
    dmode="主 D3（兜底动作本身造成错误）；次 D4（状态码写错）",
    flows=["搜索", "取消"],
    trigger="basic 返回 status 0 或反序列化失败（搜索侧）；取消链路下游快速失败如拒连、无可用实例（取消侧）。",
    consequence="搜索侧：travel 把依赖故障翻译成 HTTP 200 加空列表，按状态码算的 SLO 把它算成成功，用户看到的是「没有车次」。取消侧：入口 catch 把任何异常包装成 {\"status\":1,\"msg\":\"error\"} 并回 200，注入期间 cleanup-order 成功率仍接近 100%。两者合起来使评测对整类故障失明，直接损害基准的可观测性。",
    level_why="代码路径已核实。取消侧只掩盖快速失败——下游挂住超过 10 s 时负载端先超时，反而可见，这一半属未核实。",
    evidence=[
        "TT源码/ts-travel-service/src/main/java/travel/service/TravelServiceImpl.java:345-365（没有 try；basic 返回 status 0 或反序列化失败都变成「成功+空列表」）",
        "TT源码/ts-cancel-service/src/main/java/cancel/controller/CancelController.java:45-51（catch Exception 后 ok(Response(1,\"error\",null))，已核对上游源码逐行确认）",
        "TT源码/ts-cancel-service/src/main/java/cancel/service/CancelServiceImpl.java:245-249 等 5 处 restTemplate.exchange 均无 try",
        "D0/environment/workloads/train-ticket/image/train_ticket_workload_generator.py:285-289（负载以 status==1 判成功）",
    ],
    original_ids=["TT-B14", "TT-D1"],
    notes="两条是同一反模式在两条链路上的实例：把依赖故障映射成成功响应。合并后作为「灰色故障」的代表条目。这条对基准平台本身危害最大——注入了故障但 SLO 看不见。",
),
dict(
    id="TT-16", system=S, level="S",
    title="降级只兜「逻辑失败」不兜传输异常，非关键依赖被同步串在关键路径上",
    family=["fallback_degradation"], families=["fallback_degradation"],
    dmode="主 D1（缺降级）；次 D2（回退不覆盖传输异常）",
    flows=["下单", "取消", "搜索", "登录"],
    trigger="非关键依赖（price、user、verification-code、order-other、inside-payment）出现传输异常或 5xx，而不是返回 status 0。",
    consequence="price 故障让查询 100% 失败（降级只兜住「缺配置」、兜不住「调用失败」，try 外面抛 NPE）；user 故障把已经提交的下单或取消报成失败；order-other 单副本不可用时安检第 1 步无降级，G/D 下单 100% 失败；取消路径对 0 元退款也同步调 inside-payment、对已注释掉的通知仍同步查 user。seat 的 2N 次调用里任一失败整个查询就 500——按车次隔离的写法只存在于没人调用的 left_parallel 路径。",
    level_why="全部是源码层推断，没有实跑注入。TT-A14（登录依赖验证码）已被运行时部分否定：Jaeger 显示基准负载的登录只有网关→auth 一跳，只在 UI 带验证码时才成立。",
    evidence=[
        "TT源码/ts-basic-service/src/main/java/fdse/microservice/service/BasicServiceImpl.java:272、:457-483、:286（price 结果为 null 时抛 NPE）",
        "TT源码/ts-preserve-service/src/main/java/preserve/service/PreserveServiceImpl.java（副作用之后才查 user，结果被丢弃且无降级）",
        "TT源码/ts-travel-service/src/main/java/travel/service/TravelServiceImpl.java:367-375（seat 逐车次循环没有 try；left_parallel 才有隔离写法）",
        "TT源码/ts-cancel-service/src/main/java/cancel/service/CancelServiceImpl.java:201-203、:63-64（0 元也调 drawback）、:70-73（G/D 分支查 user）、:86-87（发邮件已注释）",
        "TT源码/ts-security-service/src/main/java/security/service/SecurityServiceImpl.java（安检第 1 步调 order-other，无降级）",
    ],
    original_ids=["TT-A5", "TT-A14", "TT-B09", "TT-B10", "TT-C10", "TT-D6"],
    notes="六条的共同模式是「有降级代码但覆盖面不对」。A14 保留在本条内但标注已被运行时部分否定（见 TT-X3）。C10 的安检阈值默认无限大（安检只剩成本不产生拦截）也并入本条备注。",
),
dict(
    id="TT-17", system=S, level="S",
    title="seat→config：一个常量配置每次都远程读取，每次查询读 2N 次，没有缓存也没有默认值，配置缺失直接 NPE",
    family=["fallback_degradation", "other（扇出放大）"], families=["fallback_degradation", "other"],
    dmode="主 D1；次 D6",
    flows=["搜索", "下单"],
    trigger="config 服务或它的库不可用，或配置项缺失。",
    consequence="DirectTicketAllocationProportion 是个常量，却每次分座都远程读一次，一次查询读 2N 次。没有缓存也没有默认值，配置缺失时在 SeatServiceImpl 直接抛 NPE，余票查询和下单的 trip_detail 一起全挂。",
    level_why="源码路径已核实，但 config 故障没有实跑。",
    evidence=[
        "TT源码/ts-seat-service/src/main/java/seat/service/SeatServiceImpl.java:190、:205-219（GET /configs/DirectTicketAllocationProportion，没有 try，配置缺失抛 NPE）",
    ],
    original_ids=["TT-B08"],
    notes="静态报告给 B08 的 E1 区间是 :205-215 而 E2 说 NPE 在 :217，落在区间外，疑似笔误；这里按 :205-219（调用图表格的写法）记录，实际行号待核。",
),

# ============================ 五、幂等、补偿与资金一致性 ============================
dict(
    id="TT-18", system=S, level="S",
    title="下单后置调用失败无补偿、取消只改状态不回收：已落库订单回 500，附属记录和座位都没人回收",
    family=["idempotency_compensation"], families=["idempotency_compensation"],
    dmode="主 D2；次 D1",
    flows=["下单", "取消"],
    trigger="写单之后的 4 个后置调用遇到传输异常或 5xx（代码只把 status≠1 当软失败）；或下单中途失败、压测异常退出。",
    consequence="订单已经写进库，接口却返回 500 且没有补偿，调用方重试会再下一单。取消时只把订单状态改掉，不回收保险、餐食、托运，也不释放座位；下单中途失败留下的 NOTPAID 订单没有任何自动回收机制（全仓没有 @Scheduled）。",
    level_why="源码路径已核实，但没有实跑注入。旧环境留下的 9 个遗留单成因静态区分不了（可能是本条，也可能是负载在下单与取消之间中断），需要按单号查 Jaeger/Loki。",
    evidence=[
        "TT源码/ts-preserve-service/src/main/java/preserve/service/PreserveServiceImpl.java:207-212（只处理 status≠1，不处理异常）",
        "TT源码/ts-cancel-service/src/main/java/cancel/service/CancelServiceImpl.java:57→:238-252（只改订单状态）",
        "TT源码/ts-order-service/src/main/java/order/service/OrderServiceImpl.java:302-311（订单只增不删）",
    ],
    original_ids=["TT-C2", "TT-C8"],
    notes="C2 是后置调用失败、C8 是补偿覆盖不全，同属「写了一半没人收尾」，合并。座位不释放这一点与 TT-35 的超卖是同一段代码的两面。",
),
dict(
    id="TT-19", system=S, level="S",
    title="全链路没有幂等键：重复提交必然重复下单，跨服务「先读后写」的守卫在慢写时会重复退款、重复扣款",
    family=["idempotency_compensation", "retry_backoff"], families=["idempotency_compensation", "retry_backoff"],
    dmode="主 D4（守卫非原子、写端无版本号）；次 D3、D5",
    flows=["下单", "取消", "支付", "改签"],
    trigger="调用方在模糊失败后重复提交；或对 order 的 PUT 注入 ≥10 s 延迟，客户端超时后重发。order-service 写端无条件覆盖，没有乐观锁，守卫全部基于旧读。",
    consequence="下单侧：去重比较写错了永远不会命中，订单号还被服务端重新生成，必然多出一笔重复订单。资金侧：两个请求都读到「已支付」就退两次款；execute 与 cancel 并发时已检票的订单会被改为 4 并退 80%；cancel 的整单 PUT 还会回滚并发改签刚写入的车次和座位。买保险是带副作用的 GET 且 Ribbon 会对 GET 自动重试一次。",
    level_why="写端与守卫的代码路径已核实。但重复请求的来源未核实：默认负载并发 1 且不重试，网关也没有 Retry 过滤器，需要真实用户重复点击或自定义客户端。Ribbon 是否真带自动重试取决于 spring-retry 是否传递进 classpath，未核实。",
    evidence=[
        "TT源码/ts-order-service/src/main/java/order/service/OrderServiceImpl.java:315-327（直接改状态）、:440-468（整单覆盖，无乐观锁）",
        "TT源码/ts-preserve-service/src/main/java/preserve/service/PreserveServiceImpl.java（无幂等键，去重比较恒不命中）",
        "TT源码/ts-inside-payment-service/src/main/java/inside_payment/controller/InsidePaymentController.java:62-66（退款接口是 GET）",
        "D0/environment/workloads/train-ticket/image/train_ticket_workload_generator.py:584-585（负载不重试，可作阴性对照）",
    ],
    original_ids=["TT-C3", "TT-C13", "TT-D5", "TT-D12"],
    notes="C3（下单去重写错）、C13（保险 GET 被重试）、D5（守卫非原子）、D12（退款 GET 被重试）是同一根因——没有幂等键 + 非幂等操作用 GET 暴露。D12 报告自评低置信，合并后整条按最弱环节定 S。",
),
dict(
    id="TT-20", system=S, level="S",
    title="取消是「先改成已取消、再退款」，退款失败只记日志仍报成功，没有补偿也没法对账",
    family=["idempotency_compensation"], families=["idempotency_compensation"],
    dmode="主 D1（扣款后中止、无补偿）；次 D2",
    flows=["取消"],
    trigger="取消进行中对 inside-payment 注入 abort 或 pod-kill，或让它到 tsdb-mysql:3306 丢包。",
    consequence="三种终态都对用户报成功：①PUT 失败→订单仍未取消；②③PUT 成功但退款返回 0 或抛异常→订单已取消而没有退款行。守卫只放行状态 0/1/3，订单已是 4 时重试会被拒，无法补救。inside_money 表只有 id/userId/money/type 四列、没有 orderId，根本没法按订单对账。",
    level_why="代码路径已核实。默认负载取消的是未支付订单，退款额为 0.00，只少一条 0 元记录；要丢真金白银需自定义 preserve→pay→cancel 流，没有实跑。",
    evidence=[
        "TT源码/ts-cancel-service/src/main/java/cancel/service/CancelServiceImpl.java:57→:238-252（先 PUT 状态 4）→:63-64（后退款）",
        "TT源码/ts-cancel-service/src/main/java/cancel/service/CancelServiceImpl.java:89-92、:122-127（退款失败只 LOGGER.error 仍返回 status 1）",
        "TT源码/ts-inside-payment-service/src/main/java/inside_payment/entity/Money.java:19-41（inside_money 无 orderId 列）",
    ],
    original_ids=["TT-D2"],
    notes="与 TT-15 的关系：本条的失败之所以对外不可见，正是因为被 TT-15 的 status=1 包装掩盖，两条在同一次注入里会同时出现。",
),

dict(
    id="TT-21", system=S, level="S",
    title="改签先动钱后改单且失败不回滚，「只能改一次」的守卫最后才落地；跨类改签用 POST 打 @DeleteMapping 必然 405",
    family=["idempotency_compensation"], families=["idempotency_compensation"],
    dmode="主 D1；次 D2",
    flows=["改签"],
    trigger="确定性触发：把 G/D 车次改签成更便宜的 Z/K/T 车次，每调一次退一次差价而订单不变。故障触发：同类改签时让 route 返回 status 0（触发 NPE），或对 seat / order 的 PUT 注入 abort。",
    consequence="钱已经动过而订单没改，守卫要求状态为 1、状态 3 只在成功路径写入，所以失败后订单仍是 1，可以反复改签、反复退差价，错误提示还在引导用户重试。跨类改签删单用 POST 打 @DeleteMapping，405 抛异常时钱已经动过；即使删除成功，delete/create 的返回值被忽略直接报 Success，删除成功但新建失败时订单就丢了。补差价还不校验余额（BigDecimal.add 结果被丢弃）。",
    level_why="源码路径已核实。跨类改签的 405 依赖 1.0.1/1.0.2 镜像没改过删除接口映射——镜像比对显示 order/controller/OrderController.class 相对上游确有差异，因此这一条在部署镜像上未核实。",
    evidence=[
        "TT源码/ts-rebook-service/src/main/java/rebook/service/RebookServiceImpl.java:127→:131、:176→:177（先动钱后改单）",
        "TT源码/ts-rebook-service/src/main/java/rebook/service/RebookServiceImpl.java:53、:69-71、:191、:222（守卫要求状态 1，状态 3 只在成功路径写入）",
        "TT源码/ts-rebook-service/src/main/java/rebook/service/RebookServiceImpl.java:371-375（POST 删单）对 TT源码/ts-order-service/src/main/java/order/controller/OrderController.java:142（@DeleteMapping）",
        "证据/TT-rebuilt-image-provenance/partial/summary-deployed-scan.txt（ts-order-service:1.0.1 的 OrderController.class 与上游编译结果不同）",
    ],
    original_ids=["TT-D3"],
    notes="本条是全审计中唯一「确定性可触发、不需要注入」的资金缺陷（跨类改签只要调用就退钱不改单），但默认负载没有改签步骤，需要自定义负载。",
),
dict(
    id="TT-22", system=S, level="S",
    title="支付部分失败后重试，被 payment 的订单号去重以「失败」拒绝：订单永远付不了而用户已被记账",
    family=["idempotency_compensation"], families=["idempotency_compensation"],
    dmode="主 D3（去重被触发却用失败回应合法重试）；次 D4、D5、D1",
    flows=["支付"],
    trigger="自定义支付负载并制造余额不足；pay 期间对 order 的 GET /order/status 注入 abort，然后客户端重试 pay。",
    consequence="站外分支顺序是扣款→本地记账→改单，改单抛异常时前两步已落地而订单仍未支付。重试能通过入口守卫，但 payment 查到已有记录就返回 0 并提示「order not found」（与事实相反），此后每次都失败，钱扣了、订单永远付不了。orderId 没有唯一约束，并发插两行后单值查询会抛异常，该订单此后永久 500。余额分支则先改单后记账，本地库故障时订单已支付却没有扣款记录。",
    level_why="上游源码路径已核实，但线上 payment 是 1.0.2，镜像比对显示 PaymentServiceImpl.class 与 PaymentRepository.class 相对上游都有差异，pay 逻辑可能已被改过——结论以上游为准，部署镜像上未核实。",
    evidence=[
        "TT源码/ts-inside-payment-service/src/main/java/inside_payment/service/InsidePaymentServiceImpl.java:110-114→:119-120→:121（扣款、记账、改单三步）",
        "TT源码/ts-payment-service/src/main/java/com/trainticket/service/PaymentServiceImpl.java:35、:43-44（查得到就返回 0 并提示 order not found）",
        "TT源码/ts-payment-service/src/main/java/com/trainticket/entity/Payment.java:29-30（orderId 无唯一约束）",
        "证据/TT-rebuilt-image-provenance/partial/summary-deployed-scan.txt（ts-payment-service:1.0.2 的 PaymentServiceImpl/PaymentRepository/PaymentController 与上游编译结果不同）",
    ],
    original_ids=["TT-D4"],
    notes="这是「待镜像比对」影响最大的一条：结论直接建立在 PaymentServiceImpl.pay 的实现上，而这个类恰好是 1.0.2 改过的类之一。见附录 E。",
),
dict(
    id="TT-23", system=S, level="S",
    title="注册是跨库双写且没有补偿，用户名也没有唯一约束：一次部分失败加一次重试，该用户就永久登录不了",
    family=["idempotency_compensation"], families=["idempotency_compensation"],
    dmode="主 D1",
    flows=["注册"],
    trigger="注册时远程建 auth 用户成功但后续失败并重试；或空库上两个 auth 副本同时启动初始化。",
    consequence="同名用户重复，该用户此后永久登录不了。",
    level_why="源码路径已核实，未实跑。",
    evidence=[
        "TT源码/ts-auth-service/src/main/java/auth/service/impl/UserServiceImpl.java:52-65（跨库双写无补偿）",
        "TT源码/ts-auth-service/src/main/java/auth/entity/User.java:32-33、UserRepository.java:20（用户名无唯一约束）",
        "TT源码/ts-auth-service/src/main/java/auth/init/InitUser.java:29-49（两副本同时初始化）",
    ],
    original_ids=["TT-A15"],
    notes="与 SS-10（user 唯一索引只在启动时建一次）是跨系统的同构缺陷。",
),
dict(
    id="TT-24", system=S, level="S",
    title="餐食配送消息：生产端落库后才发布、异常被吞、无 confirm/outbox，消费端 AUTO ack 吞掉落库异常，消息静默丢失",
    family=["delivery_semantics"], families=["delivery_semantics", "fallback_degradation"],
    dmode="主 D1（N-02：生产者无确认）；次 D2（失败不回传）、D5",
    flows=["餐食配送", "下单"],
    trigger="把负载改成带餐（默认 foodType=0，preserve 直接跳过这一步）。然后 pod-delete rabbitmq，或让 delivery 到 tsdb-mysql:3306 不通。",
    consequence="生产端：发送异常只记日志仍报成功，订餐成功但配送记录静默缺失；同步发布还会让带餐下单卡约 60 s（amqp 建连超时）。消费端：落库异常被 catch 住后正常返回，AUTO ack 照常确认，消息不会重投也没有死信队列，队列 messages_ready 始终为 0——从队列指标完全看不出丢了消息。两端都没有去重。",
    level_why="源码与 yml 已核实（两端都没有 listener / publisher confirm 配置）。默认负载不带餐，本轮没有激活这条链路。",
    evidence=[
        "TT源码/ts-food-service/src/main/java/foodsearch/service/FoodServiceImpl.java:131（落库）、:142-146（发送异常只记日志）、:148（仍报成功）",
        "TT源码/ts-food-service/src/main/resources/application.yml:22-24（只有 host/port，Boot 2.3 默认不开 publisher confirm/returns）",
        "TT源码/ts-delivery-service/src/main/java/delivery/mq/RabbitReceive.java:49-54（catch 后正常返回）",
        "TT源码/ts-delivery-service/src/main/resources/application.yml:16-18（无 listener 配置，默认 AUTO ack）",
        "D0/environment/workloads/train-ticket/image/train_ticket_workload_generator.py:382（foodType=0）",
    ],
    original_ids=["TT-D8", "TT-D9", "TT-C14"],
    notes="D8 生产端、D9 消费端、C14 同步投递卡 60 s，是同一条消息链路的三段，合并。rabbitmq 本身的单点问题在 TT-25。sock-shop 的 SS-07 是同构缺陷（shipping 吞掉发布异常仍回 201）。",
),
dict(
    id="TT-25", system=S, level="C",
    title="rabbitmq 单实例、没有持久卷、没有内存上限、只有 TCP readiness 且无 liveness：重建即丢光在途消息",
    family=["replica_disruption", "resource_limit", "health_probe"],
    families=["replica_disruption", "resource_limit", "health_probe"],
    dmode="主 D1（T-10、T-06 实例）；次 D4",
    flows=["餐食配送"],
    trigger="pod-delete rabbitmq（带餐负载下）。",
    consequence="队列按 durable 声明、消息默认持久化，但都落在容器可写层，没有卷等于形同虚设：重建后 messages=0。已预取到消费者（默认 prefetch 250）未处理完的消息本应由 broker 重投，但 broker 已经换了，于是丢失。优雅删除时消费者在 broker 就绪后 ≤5 s 恢复；节点失联这类半开连接要等 60 s 心跳约两个周期（约 120 s）。没有 memory limit 时高水位按节点内存算，流控几乎不会先于节点驱逐触发。",
    level_why="清单配置已核实（无 volumes、replicas=1、无 PDB、无 memory limit、readiness 仅 tcpSocket 5672、无 liveness）。重建丢消息没有实跑，因为默认负载不带餐。",
    evidence=[
        "清单/train-ticket/deployments.json（rabbitmq 无 volumes、replicas=1、requests 100m/200Mi 无 limit、readiness 仅 tcpSocket 5672、无 liveness）",
        "TT源码/ts-food-service/src/main/resources/application.yml:22-24 等（各服务都没有 listener 配置，取 Spring AMQP 2.2 默认值）",
    ],
    original_ids=["TT-D10", "TT-E15"],
    notes="D10 从消息链路、E15 从基础设施记同一对象，合并。「消费方能自动重连」（容器每 5 s 无限重试）是有效保护，可作 N-04 / T-07 的阴性对照。",
),

# ============================ 六、资源、老化与准入 ============================
dict(
    id="TT-26", system=S, level="C",
    title="订单表只增不减：余票查询与管理查询的成本随运行时长单调上升，各 episode 的基线不可比",
    family=["resource_limit", "load_shedding_admission"], families=["resource_limit", "load_shedding_admission"],
    dmode="主 D1；次 D5",
    flows=["搜索", "查单", "取消", "管理后台"],
    trigger="长时间跑默认负载即可，不需要注入。取消只改状态不删订单（约 1,080 单/小时），重置时 PVC 受保护，数据跨 episode 保留。",
    consequence="余票计算按 (日期, 车次) 查订单表且不过滤订单状态、没有索引，一次搜索要打 order 2N 次全表扫描，成本随历史订单线性增长。inside_money 每次取消追加一行，而退款的「账户存在」检查每次全量加载该用户全部记录（对 List 做 != null 判断，恒真）。admin-order 无分页地全量拉两张订单表。结果是取消与搜索的 p95 随运行时长漂移，基准的各 episode 之间不可比——这是对评测有效性的直接损害。",
    level_why="运行时已核实数据只增（基线期间 orders 92 行、inside_money 89 行且持续增长），PVC 保护配置已核实。老化到 GC 抖动或 OOM 的程度没有实跑。",
    evidence=[
        "TT源码/ts-order-service/src/main/java/order/service/OrderServiceImpl.java:54-71、:302-311（按日期车次查、无索引不过滤状态；findAll 无分页）",
        "TT源码/ts-inside-payment-service/src/main/java/inside_payment/service/InsidePaymentServiceImpl.java:246、:247-251（每次取消 +1 行；存在性检查全量加载且恒真）",
        "D0/environment/applications/train-ticket.yaml:109-110（重置时 PVC 受保护）",
        "证据/TT-tsdb-runtime-config/myisam-locks-during-baseline.txt（09:24Z，orders 92 行、inside_money 89 行）",
    ],
    original_ids=["TT-B12", "TT-D7", "TT-D14"],
    notes="三条都是「数据只增导致的老化」，合并。order 接收队列停止排空是这条的极端后果，因为触发条件和现象都不同，单列为 TT-27。",
),
dict(
    id="TT-27", system=S, level="C",
    title="order 接收队列停止排空、CLOSE_WAIT 与句柄堆积且不自愈，只能人工重启",
    family=["load_shedding_admission", "health_probe", "resource_limit"],
    families=["load_shedding_admission", "health_probe", "resource_limit"],
    dmode="主 D5（多因素组合）；次 D1、D4",
    flows=["下单", "查单", "搜索"],
    trigger="订单累计到 10^4–10^5 行后跑基线，再对 tsdb 主库注入 CPU 压力或 200 ms 延迟。机制是「请求线程里的无界等待 + 调用方放弃后服务端不中止 + 没有 liveness」三者组合。",
    consequence="两个副本同时 0/2，下单、查单、搜索一起超时失败，TCP 探针失败后 Pod 被摘除但没有 liveness 不会重启，只能人工干预。这条能同时解释 CLOSE_WAIT 堆积、句柄耗尽和队列不排空三个现象。",
    level_why="旧环境发生过（08-21），配置层根因已核实。本轮基线下没有复现：close-wait-during-baseline.txt 显示 order×2、gateway×1 的 CLOSE_WAIT 都是 0，Hikari 也没有排队——属于 3.2 节「基线下没复现，不能判否」。具体卡在哪里需要线程栈确认。",
    evidence=[
        "证据/TT-network-and-health/close-wait-during-baseline.txt（09:24Z，order×2、gateway×1 CLOSE_WAIT=0）",
        "证据/RES-resource-pool-metrics/during-baseline-0918.txt（15 分钟内无排队等连接）",
        "TT源码/ts-order-service/src/main/java/order/repository/OrderRepository.java:24、26（全表扫描）",
        "清单/train-ticket/deployments.json（readiness tcpSocket:12031，无 livenessProbe）",
    ],
    original_ids=["TT-C1", "TT-E06"],
    notes="C1 从下单链路、E06 从配置层记同一现象，合并。这是「S 级里最值得做注入验证」的一条：机制链完整，但基线下三个现象全部为 0。",
),
dict(
    id="TT-28", system=S, level="C",
    title="JVM 堆固定 200MB 而容器上限 1500Mi：堆内 OOM 对 K8s 不可见，进程不退出又没有 liveness，服务僵死不重启",
    family=["resource_limit", "health_probe"], families=["resource_limit", "health_probe"],
    dmode="主 D4（配额与运行时参数错配）；次 D1、D2",
    flows=["全部"],
    trigger="大响应、全量订单查询或入口压测把堆压到 -Xmx200m 上限。",
    consequence="容器 1500Mi 的配额轮不到 OOMKill，堆内 OOM 后进程和端口都还在，TCP 探针照样通过，僵尸实例继续接流量。Dockerfile 没有 -XX:+ExitOnOutOfMemoryError。网关是 -Xmx1024m 加默认直接内存，可能超出容器上限。",
    level_why="运行时已核实堆上限：ts-* 为 192–196Mi、网关 999Mi，而 request 100Mi、limit 1500Mi，实际工作集 465–859Mi。堆内 OOM 后果没有实跑。",
    evidence=[
        "证据/RES-resource-pool-metrics/during-baseline-0918.txt（ts-* 堆上限 192–196Mi、网关 999Mi；req 100Mi、lim 1500Mi；wss 465–848Mi）",
        "证据/RES-resource-pool-metrics/steady-state-0916-0931.txt（09:16–09:31，wss 490–859Mi）",
        "TT源码/ts-order-service/Dockerfile:6（-Xmx200m，无 ExitOnOutOfMemoryError）",
        "清单/train-ticket/deployments.json（无 livenessProbe）",
    ],
    original_ids=["TT-B15", "TT-C12", "TT-E11", "TT-E17"],
    notes="四组各记一次。E17 的「java:8-jre 不感知容器」部分已被运行时否定（实际是 Temurin 8u482，见 TT-X2），本条只保留堆与容器配额错配的部分。CPU 节流部分并入 TT-29。",
),
dict(
    id="TT-29", system=S, level="C",
    title="资源请求严重失真（CPU 10m / 内存 100Mi）：稳态不节流，但全量重启时 41 个 JVM 同时冷启动形成恢复风暴",
    family=["resource_limit"], families=["resource_limit"],
    dmode="主 D5（恢复期资源争用）；次 D4",
    flows=["全部"],
    trigger="节点故障重新调度，或平台重置流程 restart-application-deployments 触发全量重启。",
    consequence="request 只有 10m/100Mi 而实际工作集 465–859Mi，调度器按失真的请求值堆放 Pod。41 个 JVM 加 javaagent 同时冷启动时 CPU 争用剧烈，冷启动首请求约 9.7–10 s，正好撞上压测客户端 10 s 超时（见 TT-13）。",
    level_why="**部分更正静态结论**：运行时实测稳态下没有任何 TT Pod 节流超过 1%，节流只出现在 JVM 启动期（travel 26%、assurance 22%、auth 22% 的窗口含 09:07–09:10 重启期）。所以「稳态被节流」不成立，成立的是「恢复期风暴」。",
    evidence=[
        "证据/RES-resource-pool-metrics/steady-state-0916-0931.txt（09:16–09:31，TT 无 Pod 节流 >1%）",
        "证据/RES-resource-pool-metrics/during-baseline-0918.txt（节流 >1% 的窗口含 09:07–09:10 重启期：travel 26%、assurance 22%、auth 22%）",
        "证据/TT-baseline-abort-first-run.txt（冷启动首请求 9712–10011 ms）",
        "清单/train-ticket/deployments.json（ts-* request 10m/100Mi、limit 1.5 核/1500Mi）",
    ],
    original_ids=["TT-A11", "TT-E13"],
    notes="A11 关注网关的 request/堆错配，E13 关注恢复风暴。运行时数据把「稳态节流」这一半否定了，合并后只保留恢复期这一半，这是本轮对静态结论的一处重要收窄。",
),
dict(
    id="TT-30", system=S, level="C",
    title="没有 PDB、41 个服务单副本、多副本服务和三成员仲裁组都没有反亲和，本地盘还把 MySQL 钉在节点上",
    family=["replica_disruption"], families=["replica_disruption"],
    dmode="主 D1（T-06 实例）；次 D2、D6",
    flows=["全部"],
    trigger="排空一个节点，或 kill 任一单副本服务。新环境只有 2 个节点，TT 的 Deployment 又都被固定在 vm-0-10（偏差 #8）。",
    consequence="下单关键路径上有 6 个单副本依赖，任一重启就中断下单且不能自愈。排空承载 2 个 tsdb 成员的节点时，xenon 失去多数派，写入全断，而本地盘让被驱逐的成员只能等原节点回来。三个 MySQL 副本的数据卷在旧环境还都落在同一个 NFS 供给器上，副本不是独立故障域。",
    level_why="运行时已核实：两个命名空间都没有 PDB；副本数已从旧环境注解逐个核实（gateway 3、ui-dashboard 3、auth/order/preserve 各 2，其余 43 个为 1）。节点排空没有实跑。",
    evidence=[
        "证据/SS-runtime-config/versions-and-config.txt（08:59Z，两个命名空间都无 PDB）",
        "旧环境 Deployment 注解 resiliencebenchmark.io/standby-replicas（本轮只读核实：gateway 3、ui-dashboard 3、auth 2、order 2、preserve 2，其余 43 个为 1）",
        "清单/train-ticket/deployments.json（无反亲和）",
        "清单/train-ticket/statefulsets.json（三成员仲裁组无反亲和；旧环境三个 MySQL 数据卷同一 NFS 供给器）",
        "DEVIATIONS.md 偏差 #8（新环境 TT 的 Deployment 与 nacos 固定在 vm-0-10）",
    ],
    original_ids=["TT-A13", "TT-B07", "TT-C11", "TT-E09", "TT-E16", "TT-D13（部分）"],
    notes="**更正静态结论**：TT-B07 说「查询链路上 9 个服务都是单副本」，但 order 实际是 2 副本（已用旧环境注解核实）；任务描述里的「gateway 2、order 3」也与实际相反。E16（数据卷同一 NFS 供给器）只在旧环境成立，新环境用 openebs-hostpath，已被偏差 #1 改变。",
),

dict(
    id="TT-31", system=S, level="S",
    title="网关唯一的准入保护 Sentinel 只覆盖 39 条路由中的 1 条，登录每次都做 BCrypt 却完全不限流",
    family=["load_shedding_admission"], families=["load_shedding_admission"],
    dmode="主 D2；次 D4",
    flows=["登录", "全部"],
    trigger="登录流量激增或节点 CPU 受压。",
    consequence="BCrypt 是故意设计成慢的，每次登录都算一遍而没有任何限流，登录时延在 CPU 争用时飙升并拖累整个入口。Sentinel 只给一条管理路由限了流，对 SLO 路径没有保护。",
    level_why="路由配置与 BCrypt 调用已核实，未实跑加压。",
    evidence=[
        "TT源码/ts-gateway-service/src/main/resources/application.yml:16–209（39 条路由，Sentinel 只覆盖 1 条）",
        "TT源码/ts-auth-service/src/main/java/auth/service/impl/TokenServiceImpl.java:65-79（每次登录做 BCrypt）",
        "证据/TT-call-graph-baseline/fanout.txt（登录 HTTP 1 跳、DB 3 次）",
    ],
    original_ids=["TT-A10", "TT-E14（部分）"],
    notes="E14 的无超时部分并入 TT-11，限流部分在这里。",
),
dict(
    id="TT-32", system=S, level="S",
    title="验证码的匿名接口每次都新建 HttpSession（保留 30 min），堆只有 200m 又没有限流",
    family=["load_shedding_admission", "resource_limit"], families=["load_shedding_admission", "resource_limit"],
    dmode="主 D1",
    flows=["登录", "其他"],
    trigger="对无限流的匿名验证码接口持续 50 QPS 请求 30 分钟。",
    consequence="按 30 分钟会话保留期估算累积约 9 万个会话，200m 堆出现 Full GC 直至 OOM。",
    level_why="接口与会话行为已核实，9 万这个量级是估算，未实跑。",
    evidence=[
        "TT源码/ts-verification-code-service/src/main/java/verifycode/controller/VerifyCodeController.java:37-38、:55（匿名接口每次新建 HttpSession）",
        "TT源码/ts-verification-code-service/Dockerfile:6（-Xmx200m）",
    ],
    original_ids=["TT-A18"],
    notes="不在 SLO 路径上（基准负载的登录不带验证码），属于「可被外部流量打爆的旁路」。",
),
dict(
    id="TT-33", system=S, level="R",
    title="ticket-office 每空闲 8 小时崩一次：单条 MySQL 连接被 wait_timeout 断开、代码没有 error 监听，进程直接退出",
    family=["fallback_degradation", "replica_disruption（重启恢复）"], families=["fallback_degradation", "replica_disruption"],
    dmode="主 D3；次 D4",
    flows=["其他"],
    trigger="进程空闲满 wait_timeout=28800 s（8 小时）。驱动报 PROTOCOL_CONNECTION_LOST，回调里 throw err 打崩整个进程，靠 CrashLoopBackOff 恢复。",
    consequence="本轮已复现并计数：每次重启都会再插一行种子数据，已累计 4 行。服务本身不在 SLO 路径上，但「每次重启重复插种子数据」会污染数据集，而且这是一个可预测的周期性崩溃。",
    level_why="本轮新环境复现，机制与触发条件都已查清，并给出可证伪预测：下一次崩溃约在 2026-09-19 08:29 UTC（restartCount 应从 2 变 3，ts.office 表应从 4 行变 5 行）。**本轮未能验证该预测**——见附录 E 的未核实清单。",
    evidence=[
        "证据/TT-ticket-office-idle-connection-crash/README.txt（机制、触发条件、已累计 4 行种子数据、可证伪预测）",
        "证据/TT-tsdb-runtime-config/tsdb-leader.txt（office 表是 3 张 InnoDB 之一）",
    ],
    original_ids=["TT-B17"],
    notes="静态报告只写到「一条 SQL 出错就打崩进程」，运行时补上了真正的触发条件（空闲 8 小时的 wait_timeout）并升为 R。ticket-office 跑的是 Node v25.8.1（Dockerfile 用 `FROM node` 不固定版本），与上游预期版本相差很远，见附录 E。",
),
dict(
    id="TT-34", system=S, level="C",
    title="健康端点被 Spring Security 挡住返回 403，探针只能看 TCP，41 个服务全都没有 liveness",
    family=["health_probe"], families=["health_probe"],
    dmode="主 D4；次 D1",
    flows=["全部"],
    trigger="端口开着但进程已无法服务（线程耗尽、堆内 OOM、死锁）。",
    consequence="唯一能反映真实状态的 /actuator/health 返回 403，探针只能探 TCP 端口，而端口在进程僵死时照样开着。没有 liveness 意味着僵死的 Pod 永远不会被重启，会一直保持 Ready 并接收流量。",
    level_why="运行时已核实 /actuator/health 返回 403，清单里的探针配置也已核实。僵死场景没有实跑。",
    evidence=[
        "证据/TT-network-and-health/probe.txt（09:01Z，travel Pod：actuator/health 403；Temurin 1.8.0_482；otel agent 2.23.0）",
        "清单/train-ticket/deployments.json（readiness 仅 tcpSocket，d60/p10/t5/f3；无 livenessProbe）",
        "TT源码/ts-auth-service/src/main/java/auth/config/WebSecurityConfig.java:94 等（health 端点未放行）",
    ],
    original_ids=["TT-A9", "TT-B04（部分）", "TT-E04（部分）", "TT-D13（部分）"],
    notes="与 TT-02 的分工：本条是 K8s 侧的探针判定失灵，TT-02 是 Nacos 侧的健康判定失灵。两者叠加的后果是「两套健康判定都看不出问题」。",
),
dict(
    id="TT-35", system=S, level="S",
    title="占座没有预留也没有唯一约束，并发下单会超卖；余票校验写错；售罄时 seat 服务死循环",
    family=["idempotency_compensation", "load_shedding_admission"],
    families=["idempotency_compensation", "load_shedding_admission"],
    dmode="主 D4；次 D1",
    flows=["下单"],
    trigger="需要座位数很小且并发下单同一车次。默认数据下每种车型的座位数都是 Integer.MAX_VALUE，很难触发。",
    consequence="超卖；余票校验的比较写错；售罄时 seat 服务进入死循环。",
    level_why="源码路径已核实，但默认数据下触发不了，属于「需要改数据才能激活」的条目。",
    evidence=[
        "TT源码/ts-seat-service/src/main/java/seat/service/SeatServiceImpl.java:40-116（分座无预留、无唯一约束）",
        "TT源码/ts-train-service/src/main/java/train/init/InitData.java（座位数为 Integer.MAX_VALUE）",
    ],
    original_ids=["TT-C15"],
    notes="定级已按约束「拿不准往低一档」处理：机制确定但默认数据下不可达。",
),
dict(
    id="TT-36", system=S, level="S",
    title="UI 入口 nginx 单 worker、1024 连接、默认 60 s 超时、只有 TCP 探针，上游地址还只在启动时解析一次",
    family=["load_shedding_admission", "health_probe"], families=["load_shedding_admission", "health_probe"],
    dmode="主 D5；次 D4",
    flows=["UI入口"],
    trigger="网关变慢到接近 nginx 的 60 s 默认超时。",
    consequence="单 worker 的 1024 连接被占满，TCP 探针失败，Pod 被逐个摘除形成连锁压垮。上游地址只在启动时解析一次，网关 Pod 换 IP 后 nginx 不会重新解析。",
    level_why="nginx.conf 已核实，未实跑。ui-dashboard 不在压测 SLO 路径上（负载直连网关）。",
    evidence=[
        "TT源码/ts-ui-dashboard/nginx.conf:1、:4（单 worker）、:21（1024 连接）、:40-42（proxy_pass，默认 60 s）",
        "清单/train-ticket/deployments.json（ui-dashboard 只有 TCP 探针；副本数 3）",
    ],
    original_ids=["TT-A16"],
    notes="",
),
dict(
    id="TT-37", system=S, level="S",
    title="ischaos-tls-gateway 证书只在启动时加载，单副本且没有任何探针，证书过期后 TLS 全失败而 Pod 不重启",
    family=["other（证书到期）", "health_probe"], families=["other", "health_probe"],
    dmode="主 D4；次 D6",
    flows=["UI入口", "其他"],
    trigger="证书过期或被更换。镜像 tag 就叫 tls-cert-expire。",
    consequence="TLS 握手全部失败，而没有探针意味着 Pod 不会被重启，也不会从 Service 摘除。",
    level_why="清单已核实，未实跑。不在 SLO 路径上。",
    evidence=[
        "清单/train-ticket/deployments.json（ischaos-tls-gateway 单副本、无探针、镜像 tag 为 tls-cert-expire）",
    ],
    original_ids=["TT-A17"],
    notes="证书到期不属于 CODEBOOK 的九个机制族，归入 other。",
),
dict(
    id="TT-38", system=S, level="S",
    title="JWT 在每一跳都用本 Pod 时钟做零容差过期校验，过期异常还逃出了过滤器连 permitAll 接口也被拦",
    family=["other（时钟假设）", "deadline_timeout"], families=["other", "deadline_timeout"],
    dmode="主 D4；次 D6",
    flows=["登录", "全部"],
    trigger="某个 Pod 时钟偏移 ≥61 分钟（token 有效期 60 分钟 + 零容差）。",
    consequence="该 Pod 上所有带 token 的请求都判过期；异常逃出过滤器后，连本该 permitAll 的接口也会被拦，故障面比预期大。",
    level_why="源码路径已核实，时钟偏移没有实跑（也没有核实各节点的时钟同步状态）。",
    evidence=[
        "TT源码/ts-common/src/main/java/edu/fudan/common/util/JWTUtil.java:100、:101–103（零容差校验）",
        "TT源码/ts-common/src/main/java/edu/fudan/common/security/jwt/JWTFilter.java:28（异常逃出过滤器）",
    ],
    original_ids=["TT-A6"],
    notes="",
),
dict(
    id="TT-39", system=S, level="S",
    title="voucher 在单线程 Tornado 的 IOLoop 里做没有超时的阻塞调用，一个慢依赖冻结全部请求",
    family=["deadline_timeout", "circuit_isolation"], families=["deadline_timeout", "circuit_isolation"],
    dmode="主 D1（T-01 实例）；次 D4",
    flows=["其他"],
    trigger="并发调用 /getVoucher，同时给 order-service 注入延迟 d。",
    consequence="请求耗时呈 k×d 阶梯（第 k 个请求等 k×d），CPU 接近 0，就绪探针照常通过。凭证功能不可用，不影响主链路。",
    level_why="源码已核实，未实跑。requirements.txt 没有锁 tornado / pymysql 版本，实际版本未核实。",
    evidence=[
        "TT源码/ts-voucher-service/server.py:14（同步 def post）、:158-164（单 IOLoop 线程）、:64-65（urlopen 无超时）、:32/:71（每请求新建 pymysql 连接）",
        "清单/train-ticket/deployments.json（voucher 只有 TCP readiness 16101，无 liveness）",
    ],
    original_ids=["TT-D11"],
    notes="voucher 走 K8s DNS 不经 Nacos（server.py:47-48），是 TT-01 的天然阴性对照：Nacos 全停时 voucher 仍能正常启动。",
),
dict(
    id="TT-40", system=S, level="C",
    title="StatefulSet 按序启动叠加多处没有超时的循环：一个成员卡住就挡住其余成员重建",
    family=["replica_disruption（重启恢复）", "deadline_timeout"], families=["replica_disruption", "deadline_timeout"],
    dmode="主 D6；次 D5",
    flows=["全部"],
    trigger="nacosdb 无主时重建 Nacos。OrderedReady 策略加上三处无超时的等待循环，nacos-0 卡在 Init 就挡住 1 和 2。",
    consequence="服务发现中断被放大：本该只影响一个成员的问题变成整个集群起不来，再触发 TT-01 的全量 CrashLoop。",
    level_why="清单与启动脚本已核实。本轮运行时观察到相关现象：postStart 钩子没有总超时，容器停在 PodInitializing、拿不到日志、需要强删（ENV-pod-status-stuck-after-start）。但「一个成员挡住其余」的完整链条没有实跑。",
    evidence=[
        "清单/train-ticket/statefulsets.json（OrderedReady，无 podManagementPolicy: Parallel）",
        "证据/ENV-pod-status-stuck-after-start/nacos-0.txt（07:06Z，Started 但 waiting/PodInitializing；after-parallel.txt 三成员 PodInitializing，8848/9848 拒绝、7848 开）",
        "清单/train-ticket/configmaps.json（启动脚本里三处无超时循环）",
    ],
    original_ids=["TT-E12"],
    notes="",
),

# ============================ 七、已否定（X） ============================
dict(
    id="TT-X1", system=S, level="X",
    title="（已否定）Nacos 冷启动死锁",
    family=["other"], families=["other"],
    dmode="—",
    flows=["全部"],
    trigger="—",
    consequence="—",
    level_why="不成立。真因是 Nacos 的外部数据库没有建表：`Table 'nacos.config_info' doesn't exist` → `No DataSource set` → Nacos failed to start。补表后原配置在 08:57:23Z 依次就绪。偏差 #9–#11 已据此撤回。",
    evidence=[
        "证据/TT-nacos-coldstart-deadlock/root-cause-no-datasource.txt（08:49Z）",
        "证据/TT-nacos-coldstart-deadlock/README.md（冷启动死锁作废的说明）",
        "DEVIATIONS.md 偏差 #9–#11（已撤回）",
    ],
    original_ids=["偏差 #9–#11（Nacos 冷启动死锁）"],
    notes="保留在正文里便于追溯：这是本轮唯一一个被完整推翻并找到真因的判断。",
),
dict(
    id="TT-X2", system=S, level="X",
    title="（已否定）train-ticket 的 java:8-jre 基础镜像不感知容器限额",
    family=["resource_limit"], families=["resource_limit"],
    dmode="—",
    flows=["全部"],
    trigger="—",
    consequence="—",
    level_why="不成立。运行时实测容器里是 Temurin 1.8.0_482，该版本已支持 UseContainerSupport，会按容器限额而非宿主机核数配置 GC 与线程池。",
    evidence=[
        "证据/TT-network-and-health/probe.txt（09:01Z，travel Pod：Temurin 1.8.0_482；otel agent 2.23.0）",
    ],
    original_ids=["TT-E17（部分）", "TT-C12（部分）", "TT-A11（部分）", "java:8-jre 不感知容器"],
    notes="被否定的只是「不感知容器」这一半；堆 200MB 与容器 1500Mi 错配的另一半仍然成立，见 TT-28。",
),
dict(
    id="TT-X3", system=S, level="X",
    title="（部分否定）登录同步依赖验证码服务",
    family=["fallback_degradation"], families=["fallback_degradation"],
    dmode="—",
    flows=["登录"],
    trigger="—",
    consequence="—",
    level_why="在基准负载下不成立。Jaeger 显示登录只有网关→auth 一跳，负载不带验证码（generator:302-309）。只有在 UI 带验证码的路径上才成立。",
    evidence=[
        "证据/TT-call-graph-baseline/fanout.txt（登录 HTTP 1 跳，仅 gateway→auth）",
        "D0/environment/workloads/train-ticket/image/train_ticket_workload_generator.py:302-309（登录不带验证码）",
    ],
    original_ids=["TT-A14（部分）"],
    notes="代码层面的缺陷（校验恒返回 true 却被同步依赖）仍记在 TT-16 里，只是基准负载触发不到。",
),
]
