# -*- coding: utf-8 -*-
"""sock-shop 终稿条目。原编号对应 static-audit/SS-sock-shop.md 的 SS-01…SS-23。"""

S = "sock-shop"

SS_ENTRIES = [
dict(
    id="SS-01", system=S, level="R",
    title="发货链路两端都静默失败：shipping 吞掉发布异常仍回 201，queue-master 的发货必然失败却照常确认消息",
    family=["delivery_semantics", "fallback_degradation"], families=["delivery_semantics", "fallback_degradation"],
    dmode="主 D1（N-02：生产者无确认）；次 D3（兜底动作本身造成错误）、D2",
    flows=["结账", "发货"],
    trigger="不需要注入，默认负载就持续发生。queue-master 在 K8s 里必然失败——它要用 /var/run/docker.sock 起容器，而容器里根本没有这个文件。shipping 侧则在 RabbitMQ 不可用时触发。",
    consequence="本轮实测：15 分钟收到 433 条消息、失败 432 条，而同期 checkout 225 次 0 失败——发货链路末端 100% 静默失败，从业务指标上完全看不出来。队列积压始终为 0（失败消息照样 ack），shipping-task 队列 durable=false，broker 也没有卷，没有死锁队列兜底。shipping 端则是吞掉发布异常仍回 201，订单显示成功而发货消息静默丢失。",
    level_why="本轮新环境直接复现，有 baseline-0918.txt：DockerSpawner 报错 351+81=432 次，队列 messages 0 / unacked 0 / consumers 1。",
    evidence=[
        "证据/SS-queue-master-swallowed-failures/baseline-0918.txt（09:23Z，15 分钟收到 433、失败 432，/var/run/docker.sock 不存在；shipping-task durable=false；同期 checkout 225 次 0 失败）",
        "SS源码/queue-master-0.3.1/src/main/java/works/weave/socks/queuemaster/（发货异常被吞、AUTO ack）",
        "SS源码/shipping-0.4.8/src/main/java/works/weave/socks/shipping/controllers/ShippingController.java:42-48（发布异常被吞仍回 201）",
        "清单/sock-shop/deployments.json（rabbitmq 无持久卷）",
    ],
    original_ids=["SS-07", "SS-23"],
    notes="两条是同一条发货链路的前后两段（生产端 shipping、消费端 queue-master），合并。这是 sock-shop 唯一一条「默认负载下 100% 持续发生、却完全不影响 SLO」的缺陷，对基准而言是最典型的灰色故障样本。与 TT-24 是跨系统同构缺陷。",
),
dict(
    id="SS-02", system=S, level="C",
    title="front-end 的回调没有 error 兜底、先解析后判错：一个下游错误就打崩整个 Node 进程，放大成分钟级全站中断",
    family=["fallback_degradation", "circuit_isolation"], families=["fallback_degradation", "circuit_isolation"],
    dmode="主 D4（错误处理写错）；次 D5（与就绪延迟、重启退避叠加）",
    flows=["加购", "结账", "全站"],
    trigger="catalogue 不可达时，加购回调先执行 `JSON.parse(undefined)` 再判错；user 回 500 JSON、或有地址/卡但属性查询失败时回 200 却缺 `_links`，结账回调抛 TypeError。",
    consequence="整个 front-end 进程退出，而 front-end 是全站唯一入口。叠加 catalogue 的 180 秒就绪延迟和重启退避，一次 catalogue 重启会被放大成 3–7 分钟的全站中断。user-db 抖一下就能打崩全站。",
    level_why="源码路径已核实（报错栈行号 orders:67 / cart:79 / orders:91、:106）。崩溃没有实跑。量级取决于 kube-proxy 模式：Service 没有端点时是立即被拒（iptables）还是被丢包挂起（部分 IPVS/eBPF 实现），前者立刻崩、后者约 127 秒后超时再崩——未核实。",
    evidence=[
        "SS源码/front-end-0.3.12/api/cart/index.js:79（JSON.parse 在判错之前）",
        "SS源码/front-end-0.3.12/api/orders/index.js:67、:91、:106（结账回调缺 error 守卫）",
        "清单/sock-shop/deployments.json（catalogue readiness initialDelaySeconds 180）",
    ],
    original_ids=["SS-02", "SS-03"],
    notes="两条后果完全一样（进程退出→就绪延迟→退避→全站中断），报告自己也只能靠报错栈行号区分，合并。负控制：客户没有地址或卡时不会崩（返回 []、前端守卫短路、orders 以 406 拒单），真正会崩的是「有地址/卡但属性查询失败」那一支。",
),
dict(
    id="SS-03", system=S, level="C",
    title="session-db 没有持久化而 logged_in cookie 仍有效：会话一丢，customerId 变成 undefined，购物车串单并打崩结账",
    family=["replica_disruption", "fallback_degradation"], families=["replica_disruption", "fallback_degradation"],
    dmode="主 D2；次 D5",
    flows=["登录", "购物车", "结账"],
    trigger="session-db（Redis）重建。Redis 8.10.1 配的是 save \"\" 且 appendonly no，重启即清空；而客户端仍持有 logged_in cookie。",
    consequence="旧 sid 查不到就新建会话（saveUninitialized:true），customerId 成为 undefined：所有此类用户共用同一个「undefined 购物车」，互相串单；结账时让 front-end 进入崩溃循环，故障消失后也不会自动恢复——这正是「恢复后回不来」，属于要保留的例外情形。",
    level_why="Redis 持久化配置已在运行时核实（save 空、appendonly no）。串单与崩溃循环没有实跑。express-session 的实际版本待核（该行为在 1.x 中一致）。",
    evidence=[
        "证据/SS-runtime-config/versions-and-config.txt（08:59Z，session-db save 空、appendonly no；express-session 1.15.1、connect-redis 3.2.0、redis 2.7.1）",
        "清单/sock-shop/deployments.json（session-db 无持久卷、BestEffort）",
        "SS源码/front-end-0.3.12/（saveUninitialized:true）",
    ],
    original_ids=["SS-01"],
    notes="这一条是修复记录的直接后果：那次修补把 session-db 的「写不进」换成了「重启即清空」。与 TT-23（注册跨库双写）同属「身份数据不一致导致用户永久不可用」。",
),
dict(
    id="SS-04", system=S, level="C",
    title="探针判定与真实服务能力脱节：四个 Java 服务完全没有探针、自带 /health 恒回 200，front-end 探针打的是静态页",
    family=["health_probe"], families=["health_probe"],
    dmode="主 D1（T-05 实例）；次 D2、D4",
    flows=["全站"],
    trigger="session-db 挂起（连接没断）时，除静态文件外的全站请求都会挂住，而 front-end 的探针打的是静态页，始终为绿；carts/orders/shipping/queue-master 则根本没有探针。",
    consequence="服务在启动期就被当成可用；死锁、堆耗尽、依赖挂起这些情况都不会被探测到，也不会触发重启。会话降级只在「连接断开」时才生效，挂起（连接还在）时不生效。",
    level_why="清单与 /health 实现已核实。挂起场景没有实跑；express-session 在存储挂起时的行为靠库默认推断，connect-redis/redis 不在 yarn.lock 里，属未核实。",
    evidence=[
        "清单/sock-shop/deployments.json（carts、orders、shipping、queue-master 无任何探针）",
        "SS源码/carts-0.4.8/src/main/java/works/weave/socks/cart/（/health 恒返回 200）",
        "清单/sock-shop/deployments.json（front-end 探针指向静态页）",
    ],
    original_ids=["SS-18", "SS-05"],
    notes="SS-05 的出站无超时部分并入 SS-06，探针部分在这里。与 TT-34 是跨系统同构缺陷。",
),
dict(
    id="SS-05", system=S, level="C",
    title="启动不到一秒的 Go 服务配了 180 秒固定就绪延迟又没有 startupProbe，存活探针还在处理函数里同步 Ping 远程库",
    family=["health_probe", "replica_disruption（重启恢复）"], families=["health_probe", "replica_disruption"],
    dmode="主 D6；次 D4、D5",
    flows=["浏览", "结账", "登录", "全站"],
    trigger="payment、catalogue、user 任何一次重启；或它们的数据库中断约 6–9 秒（periodSeconds 3 × failureThreshold 3，按相位不同）。",
    consequence="每次重启都意味着该服务至少 3 分钟完全不可用——而实际启动只要不到一秒。探针在处理函数里同步 Ping 远程数据库，把「依赖故障」误判成「自己不健康」而自杀重启，重启后又被初始化循环和 180 秒就绪延迟拖成至少 3 分钟不可用，形成故障放大。",
    level_why="清单配置已核实。重启放大链条没有实跑。同一个 /health 端点对两类故障给出相反结论：数据库快速拒连时 Ping 立刻返回、探针恒绿；数据库慢或被黑洞时才被杀。",
    evidence=[
        "清单/sock-shop/deployments.json（payment/catalogue/user 的 readiness initialDelaySeconds 180、liveness 300，无 startupProbe）",
        "SS源码/catalogue-0.3.5/（/health 处理函数里同步 Ping 远程库）",
        "SS源码/user-0.4.7/main.go:99-110（启动初始化循环）",
    ],
    original_ids=["SS-06", "SS-04"],
    notes="标题里的时间阈值，静态报告有三种说法（约 9 秒 / 约 6–9 秒 / ≥9 秒）；按 periodSeconds×failureThreshold 推是 6–9 秒（取决于相位），这里取 6–9 秒。负控制：catalogue 启动不依赖数据库，所以这 180 秒是纯配置冗余而不是真实等待。",
),
dict(
    id="SS-06", system=S, level="C",
    title="出站调用普遍没有超时：front-end 全部出站无超时，carts/orders 的 Mongo 只设了服务器选择超时",
    family=["deadline_timeout", "circuit_isolation"], families=["deadline_timeout", "circuit_isolation"],
    dmode="主 D1；次 D2、D4",
    flows=["全站", "登录", "购物车"],
    trigger="任一下游变慢或黑洞；数据库在建连之后挂起。",
    consequence="front-end 的出站请求没有超时，Node 在 120 秒后断开客户端连接却不取消出站请求，这些请求也不进延迟直方图——故障在监控上不可见。Mongo 只配了服务器选择超时、没有读写超时，建连后库挂起时请求线程无限阻塞在 socket 读上。登录时合并购物车做了「出错就忽略」的降级却没有超时，carts 一变慢，登录就被一个非关键依赖拖住。",
    level_why="源码与配置已核实（版本在 yarn.lock 与 Dockerfile 里有据）。但行为本身靠库默认推断：request 2.x 默认不超时、Node 4 的 server.timeout=120 秒、Spring Boot 1.4.4 管理的 Mongo 驱动 3.2.x 默认 socketTimeout=0——jar 内实际驱动版本未核实。",
    evidence=[
        "SS源码/front-end-0.3.12/（所有出站调用无 timeout 参数；yarn.lock 里 request 2.81.0）",
        "SS源码/carts-0.4.8/src/main/java/works/weave/socks/cart/（Mongo 只设 serverSelectionTimeout）",
        "SS源码/front-end-0.3.12/api/user/index.js:286-293（登录合并购物车的降级只处理快速失败）",
        "证据/SS-runtime-config/versions-and-config.txt（08:59Z，Java 服务 openjdk 1.8.0_111）",
    ],
    original_ids=["SS-15", "SS-16", "SS-17", "SS-05（部分）"],
    notes="SS-16 是 SS-15 在 `GET /login → carts/merge` 这一条路由上的实例，严格子集。负控制：登录对 carts 的快速失败确有有效降级，只有「变慢或挂起」才成立。与 TT-11、TT-12 是跨系统同构缺陷。",
),
dict(
    id="SS-07", system=S, level="S",
    title="下单流程是「付款 → 发货 → 写 orders-db」，既没有补偿也没有幂等键；5 秒超时只放弃等待、不取消调用",
    family=["idempotency_compensation", "deadline_timeout"], families=["idempotency_compensation", "deadline_timeout"],
    dmode="主 D1；次 D2",
    flows=["结账"],
    trigger="orders-db 不可用或挂起；或下游慢于 5 秒。",
    consequence="钱已经付了、货已经发了，却没有订单，且没有任何补偿。5 秒超时只是放弃等待、不取消调用，底层 RestTemplate 也没有连接/读超时：下游慢于 5 秒时，被判失败的订单照样发货；下游挂起时线程随故障时长线性堆积。",
    level_why="源码路径已核实（OrdersController.java:85-117 的三步顺序）。没有实跑注入。orders 的异步执行器无上限是 Spring 默认行为推断，未在镜像内核实。",
    evidence=[
        "SS源码/orders-0.4.7/src/main/java/works/weave/socks/orders/controllers/OrdersController.java:85-117（付款→发货→写库三步，无补偿无幂等键）",
        "SS源码/orders-0.4.7/src/main/java/works/weave/socks/orders/（5 秒超时只放弃等待，不取消；SimpleAsyncTaskExecutor 无上限）",
    ],
    original_ids=["SS-08", "SS-11"],
    notes="两条引用同一段「付款→发货→落库」代码，只是失败点不同，合并。负控制：orders 等待下游确有 5 秒上限（只是不取消）。与 TT-18、TT-19 是跨系统同构缺陷。",
),
dict(
    id="SS-08", system=S, level="R",
    title="购物车明细只增不删、加购还是非原子的读-改-写，5 个虚拟用户共用一个账号的购物车",
    family=["idempotency_compensation", "resource_limit"], families=["idempotency_compensation", "resource_limit"],
    dmode="主 D1；次 D4",
    flows=["加购", "购物车", "结账"],
    trigger="默认负载就持续发生：结账只删购物车、不删明细；5 个闭环用户共用一个账号，加购的读-改-写交错。",
    consequence="本轮实测：carts-db 里 cart 表 0 条而 item 表 580 条——明细行永久泄漏，数据库单调增长。购物车懒创建且没有唯一约束，别人的清空和加购会交错进自己的订单，件数金额不确定，各 episode 之间不可比。",
    level_why="本轮新环境直接核实（cart 0 条 / item 580 条）。「超过支付限额」这一现象在修补后已不再复现（最坏 79.99 不超限），剩下的是件数金额不确定。",
    evidence=[
        "证据/SS-runtime-config/versions-and-config.txt 及 carts-db 计数（cart 0 条、item 580 条）",
        "SS源码/carts-0.4.8/src/main/java/works/weave/socks/cart/（非原子读-改-写，购物车懒创建无唯一约束）",
        "D0/environment/workloads/sock-shop/locustfile.py:32（5 个闭环用户共用一个账号）",
    ],
    original_ids=["SS-22"],
    notes="负控制：carts 会拦截缺 itemId 的写入，不写脏数据。这一条与 TT-26 同属「数据只增导致 episode 不可比」，对基准有效性的损害大于对业务的损害。",
),
dict(
    id="SS-09", system=S, level="C",
    title="有状态组件全部没有持久卷且都是 BestEffort，14 个 Deployment 全单副本、无反亲和、无 PDB",
    family=["replica_disruption", "resource_limit"], families=["replica_disruption", "resource_limit"],
    dmode="主 D1（T-06、T-10 实例）；次 D2",
    flows=["全站"],
    trigger="排空任一节点，或任一组件重建。",
    consequence="drain 一个节点即全站中断。所有数据库都没有卷、都是 BestEffort，内存压力下最先被驱逐；user-db 一重建，压测账号的地址和卡（运行期绑定的）就丢了，结账可能永久失败——这是「恢复后回不来」的又一实例。",
    level_why="运行时已核实：两个命名空间都没有 PDB，*-db / rabbitmq / session-db 都是 BestEffort。节点排空没有实跑。导出清单不含 PDB/HPA/NetworkPolicy 这类资源，PDB 的缺失是在集群上核实的。压测账号究竟是种子账号还是运行期注册的，未核实——这一点决定严重度。",
    evidence=[
        "证据/SS-runtime-config/versions-and-config.txt（08:59Z，*-db / rabbitmq / session-db 为 BestEffort；两个命名空间都无 PDB）",
        "清单/sock-shop/deployments.json（14 个 Deployment 全单副本、无反亲和、无持久卷）",
        "D0/environment/repairs/sock-shop-workload-dependency-compatibility-20260822.yaml（地址与卡运行期绑定）",
    ],
    original_ids=["SS-09", "SS-20"],
    notes="SS-20 的 E3 直接引用 SS-09，合并。与 TT-30 是跨系统同构缺陷。",
),
dict(
    id="SS-10", system=S, level="C",
    title="整条链路的错误码分类都不准，front-end 还把下游错误改写成 200：压测中一半的浏览流量对故障完全看不见",
    family=["fallback_degradation"], families=["fallback_degradation"],
    dmode="主 D4；次为潜在的 D3",
    flows=["浏览", "结账", "全站"],
    trigger="catalogue 侧任何故障；以及不可重试的客户端错误、数据库故障、带副作用的超时。",
    consequence="不可重试的客户端错误回 500，数据库故障回 404，带副作用的超时也回 500。front-end 把下游错误一律改写成 200，而浏览流量占压测的一半——对 catalogue 侧故障完全失明。错误预算、熔断决策和重试决策会一起失真。",
    level_why="分类事实已在源码里核实。危害需要有重试层才会发生，而应用层没有任何重试（T-03 重试放大不成立）——前提是没有 sidecar，这一点未核实。",
    evidence=[
        "SS源码/front-end-0.3.12/（下游错误被改写成 200）",
        "SS源码/catalogue-0.3.5/（数据库故障被报成 404）",
        "D0/environment/workloads/sock-shop/locustfile.py（浏览流量约占一半）",
    ],
    original_ids=["SS-14", "SS-13"],
    notes="SS-13 是 SS-14 总纲下的一个实例，合并。与 TT-15 是跨系统同构缺陷，两者都直接损害基准的可观测性。",
),
dict(
    id="SS-11", system=S, level="S",
    title="catalogue 熔断器的参数和错误分类都有问题：连续 6 次请求不存在的商品就让所有人 30 秒无法加购",
    family=["circuit_isolation"], families=["circuit_isolation"],
    dmode="主 D4；次 D2",
    flows=["加购", "浏览"],
    trigger="客户端连续请求 6 次不存在的商品（正常的 404 被计成失败）。",
    consequence="熔断器跳闸后所有人 30 秒内无法加购——一个客户端的错误请求能让全体用户不可用。数据库故障被报成 404 不计入失败，慢故障也不计入失败，真正该跳闸的时候反而不跳。",
    level_why="熔断器只设了 Timeout 这一点已核实，但 gobreaker 809bcd5 的源码没落地，「连续失败超过 5 次跳闸、半开只放行 1 个请求」是按文档默认值推断的，而整条候选的量级就建立在这个阈值上。",
    evidence=[
        "SS源码/front-end-0.3.12/（熔断器只设 Timeout）",
        "SS源码/catalogue-0.3.5/（数据库故障归成 404）",
    ],
    original_ids=["SS-12"],
    notes="负控制：payment 的熔断器永远不会跳闸（端点恒返回 nil error）。这条是 SS 里「保护动作本身造成故障」（D3 边界）的典型。",
),
dict(
    id="SS-12", system=S, level="S",
    title="user 的用户名唯一索引只在服务启动时建一次：user-db 重建后去重保护悄悄消失，一旦重名就永远起不来",
    family=["idempotency_compensation", "retry_backoff"], families=["idempotency_compensation", "retry_backoff"],
    dmode="主 D2；次 D5",
    flows=["注册", "登录"],
    trigger="user-db 重建后出现重名用户，然后 user 重启。当前压测不做注册，需要人或被测智能体制造重名。",
    consequence="去重保护消失后一旦出现重名，下次 user 重启会卡在一个不退避、还泄漏会话的初始化死循环里，永远起不来——「恢复后回不来」的实例。",
    level_why="代码链完整且已核实，但需要「重名注册」这个前置条件，当前负载不触发。MongoDB 3.0 起 dropDups 被忽略这一点是库行为推断。",
    evidence=[
        "SS源码/user-0.4.7/main.go:99-110（唯一索引只在启动时建一次；不退避的初始化死循环，且泄漏会话）",
    ],
    original_ids=["SS-10"],
    notes="与 SS-05 引用同一段 main.go:99-110，但那里是「能自愈」的形态（user-db 恢复后循环能退出），这里是「永不自愈」的形态。与 TT-23 是跨系统同构缺陷。",
),
dict(
    id="SS-13", system=S, level="R",
    title="CPU limit 按平均用量配、没留突发余量：5 个用户就让 carts 节流 33%、orders 24%，而平均用量只有约 0.06 核",
    family=["resource_limit"], families=["resource_limit"],
    dmode="主 D4；次 D2",
    flows=["购物车", "加购", "结账"],
    trigger="默认负载（5 个闭环用户、约 5 流程/秒）就会触发，不需要注入。",
    consequence="本轮实测：压测期间 carts 节流 33.3%（实际用量 0.061 核，limit 300m）、orders 节流 23.9%（0.054 核，limit 500m）、shipping 9.8%、queue-master 5.1%，而空闲时全部约 0%。与 GET /cart 的 P99 600 ms 同时出现。另有静态问题：JVM 堆 128 MiB 远低于 500 Mi 限额，堆内 OOM 时不退出，对 K8s 不可见。",
    level_why="节流数据本轮实测得到，压测/空闲两组对照清楚。堆内 OOM 的后果没有实跑；msd-java 基础镜像的 JDK 版本未知，Go 1.7 按宿主核数调度也是运行时默认行为推断。",
    evidence=[
        "证据/RES-resource-pool-metrics/ss-throttle-load-vs-idle.txt（压测 09:11–09:20：carts 33.3%、orders 23.9%、shipping 9.8%、queue-master 5.1%、front-end 1.9%；空闲 09:21–09:30 全部约 0%）",
        "证据/SS-baseline/locust-summary.txt（09:10:26–09:20:26，5 用户，1955 请求 0 失败；GET /cart 中位 9 ms、P99 600 ms、max 701 ms）",
        "证据/RES-resource-pool-metrics/during-baseline-0918.txt（SS 内存：carts 74%、orders 78%、queue-master 64%、shipping 69%，limit 500Mi）",
        "清单/sock-shop/deployments.json（carts limit 300m、orders limit 500m；JVM 堆 128 MiB）",
    ],
    original_ids=["SS-19"],
    notes="静态报告只写了堆与限额错配（SS-19），CPU 节流是本轮运行时新发现的，合并进来并升为 R。与 TT-29 恰好相反：TT 稳态不节流，SS 在默认负载下就节流三成。",
),
dict(
    id="SS-14", system=S, level="S",
    title="front-end 到 session-db 的重连退避没有上限，累计 1 小时后永久放弃",
    family=["retry_backoff"], families=["retry_backoff"],
    dmode="D4（N-04 实例）",
    flows=["全站"],
    trigger="session-db 断开时间较长。",
    consequence="断开越久重连越晚（退避没有最大间隔），累计 1 小时后永久放弃，期间持续返回 500 且不会自行恢复——「恢复后回不来」的实例。",
    level_why="**证据最弱的一条**：redis 库根本不在 yarn.lock 里，「退避系数 1.7、没有最大间隔、累计 1 小时后放弃」全部是 node_redis 2.x 的文档默认值推断，库版本未核实。报告自评「低到中」。",
    evidence=[
        "SS源码/front-end-0.3.12/（重连配置；库版本不在 yarn.lock 中，待核）",
        "证据/SS-runtime-config/versions-and-config.txt（08:59Z，redis(client) 2.7.1——与推断所用的 2.x 一致，但退避参数未直接核实）",
    ],
    original_ids=["SS-21"],
    notes="负控制：session-db 快速拒连时 front-end 有降级。本条按约束「拿不准往低一档」定 S，且在附录 E 里列为证据最弱的五处之一。",
),
]
